### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Yksgerisayim** [programminghoch10/HangoverClock#1]
Do you think adding public licence or other ? İ want to use your coded with some changes, My app is an exam app,when i use your codes my app does not include real time and date, İ will use your code only for count down a specific time that specified by me.So my app will not be same category with your app.Thanks

**Comment by Yksgerisayim** [comment]
Please contact me via saeyazilim at g mail com

**Comment by programminghoch10** [comment]
Please read my [LICENSE.md](https://github.com/programminghoch10/HangoverClock/blob/master/LICENSE.md), where I have explicitly stated that having no license is intentional.
